StudyIt.Web/ViewModels/GroupsViewModels.cs
using StudyIt.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace StudyIt.Web.ViewModels
{
    public class GroupsListViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public bool IsTrainer { get; set; }
    }

    public class GroupsShowViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }

    public class GroupsShowMenuViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public List<Category> Categories { get; set; }
    }
}

StudyIt.Web/Areas/GroupAdmin/Controllers/GroupController.cs
using StudyIt.Service;
using StudyIt.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebMatrix.WebData;
using StudyIt.Web.Filters;
using StudyIt.Models;
using StudyIt.Web.Helpers;

namespace StudyIt.Web.Areas.GroupAdmin.Controllers
{
    [Authorize(Roles = "GroupAdmin,Admin")]
    public class GroupController : Controller
    {
        private IGroupService groupService;
        private ICategoryService categoryService;

        public GroupController()
        {
            this.groupService = new GroupService();
            this.categoryService = new CategoryService();
        }

        public GroupController(IGroupService groupService, ICategoryService categoryService)
        {
            this.groupService = groupService;
            this.categoryService = categoryService;
        }

        //
        // GET: /GroupAdmin/Group/

        [HttpGet]
        [InitializeSimpleMembership]
        public ActionResult Index()
        {
            List<Group> groups;
            if (User.IsInRole("GroupAdmin"))
            {
                groups = groupService.GetGroupsByOwnerId(
                    WebSecurity.GetUserId(User.Identity.Name)
                    );
            }
            else
            {
                groups = groupService.GetAllGroups();

            }
            var viewModel = new List<GroupAdminGroupIndexViewModel>();
            foreach (var group in groups)
            {
                viewModel.Add(new GroupAdminGroupIndexViewModel
                {
                    Id = group.Id,
                    Name = group.Name,
                    Type = GroupTypeHelper.GroupTypeToString(group.Type),
                    Categories = categoryService.GetCategoriesByGroupId(group.Id),
                });
            }
            return View(viewModel);
        }

        //
        // GET: /GroupAdmin/Group/Create

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /GroupAdmin/Group/Create

        [InitializeSimpleMembership]
        [HttpPost]
        public ActionResult Create(GroupAdminGroupCreateViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var group = new Group
                {
                    Name = viewModel.Name,
                    OwnerId = WebSecurity.GetUserId(User.Identity.Name),
                    Type = viewModel.Type,
                };
                groupService.CreateGroup(group);
                return Redirect("/GroupAdmin/Group");
            }
            return View(viewModel);
        }

        //
        // GET: /GroupAdmin/Group/Delete/5

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var group = groupService.GetGroup(id);
            var viewModel = new GroupAdminGroupDeleteViewModel
            {
                Id = id,
                Name = group.Name,
                Type = GroupTypeHelper.GroupTypeToString(group.Type),
            };
            return View(viewModel);
        }

        //
        // POST: /GroupAdmin/Group/Delete/5

        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeleteConfirm(int id)
        {
            groupService.DeleteGroup(id);
            return Redirect("/GroupAdmin/Group/");
        }
    }
}

StudyIt.Web/Controllers/GroupsController.cs
using StudyIt.Models;
using StudyIt.Service;
using StudyIt.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace StudyIt.Web.Controllers
{
    [Authorize]
    public class GroupsController : Controller
    {
        private IGroupService groupService;
        private IUserService userService;

        public GroupsController()
        {
            this.groupService = new GroupService();
            this.userService = new UserService();
        }

        public GroupsController(IGroupService groupService, IUserService userService)
        {
            this.groupService = groupService;
            this.userService = userService;
        }

        [HttpGet]
        public ActionResult Choose()
        {
            return View();
        }

        //
        // GET: /groups/public

        [AllowAnonymous]
        [HttpGet]
        public ActionResult Public()
        {
            var groups = groupService.GetPublicGroups();
            var viewModel = new List<GroupsListViewModel>();
            bool isTrainer = false;
            UserProfile user = null;
            if (User.Identity.IsAuthenticated)
            {
                user = this.userService.GetUser((int)Membership.GetUser().ProviderUserKey);
            }
            foreach (var group in groups)
            {
                if (User.Identity.IsAuthenticated && (
                    group.Trainers.Where(x => x.UserId == user.UserId).Count() > 0 ||
                    group.TrainerQueries.Where(x => x.UserId == (int)Membership.GetUser().ProviderUserKey && x.GroupId == group.Id).Count() > 0 ||
                    group.Owner.UserId == (int)Membership.GetUser().ProviderUserKey
                ))
                {
                    isTrainer = true;
                }
                else
                {
                    isTrainer = false;
                }
                viewModel.Add(new GroupsListViewModel
                {
                    Id = group.Id,
                    Name = group.Name,
                    IsTrainer = isTrainer,
                });
            }
            return View("List", viewModel);
        }

        [HttpGet]
        [ActionName("member-of")]
        public ActionResult MemberOf()
        {
            var userId = (int)Membership.GetUser().ProviderUserKey;
            var groups = groupService.GetGroupsMemberOf((int)Membership.GetUser().ProviderUserKey);
            var viewModel = new List<GroupsListViewModel>();
            bool isTrainer = false;
            foreach (var group in groups)
            {
                if (User.Identity.IsAuthenticated && (
                   group.Trainers.Where(x => x.UserId == (int)Membership.GetUser().ProviderUserKey).Count() > 0 ||
                   group.TrainerQueries.Where(x => x.UserId == (int)Membership.GetUser().ProviderUserKey && x.GroupId == group.Id).Count() > 0 ||
                   group.Owner.UserId == (int)Membership.GetUser().ProviderUserKey
               ))
                {
                    isTrainer = true;
                }
                else
                {
                    isTrainer = false;
                }
                viewModel.Add(new GroupsListViewModel
                {
                    Id = group.Id,
                    Name = group.Name,
                    IsTrainer = isTrainer,
                });
            }
            return View("List", viewModel);
        }

        [HttpGet]
        [ActionName("not-member-of")]
        public ActionResult NotMemberOf()
        {
            var groups = groupService.GetGroupsNotMemberOf((int)Membership.GetUser().ProviderUserKey);
            var viewModel = new List<GroupsListViewModel>();
            foreach (var group in groups)
            {
                viewModel.Add(new GroupsListViewModel
                {
                    Id = group.Id,
                    Name = group.Name,
                });
            }
            return View("List", viewModel);
        }

        [AllowAnonymous]
        [HttpGet]
        public ActionResult Show(int id)
        {
            var group = groupService.GetGroup(id);
            var viewModel = new GroupsShowViewModel
            {
                Id = group.Id,
                Name = group.Name,
            };
            return View(viewModel);
        }

        [AllowAnonymous]
        public ActionResult ShowLessonsMenu(int id)
        {
            var group = groupService.GetGroup(id);
            var viewModel = new GroupsShowMenuViewModel
            {
                Categories = group.Categories as List<Category>,
                Id = group.Id,
                Name = group.Name,
            };
            return PartialView(viewModel);
        }

        public ActionResult ShowTestsMenu(int id)
        {
            var group = groupService.GetGroup(id);
            var viewModel = new GroupsShowMenuViewModel
            {
                Categories = group.Categories as List<Category>,
                Id = group.Id,
                Name = group.Name,
            };
            return PartialView(viewModel);
        }

        [AllowAnonymous]
        public ActionResult EmptyLessonsList(int groupId)
        {
            var viewModel = new List<LessonListViewModel>();
            ViewData["GroupId"] = groupId;
            return View("../Lesson/List", viewModel);
        }

        public ActionResult EmptyTestsList(int groupId)
        {
            var viewModel = new List<TestListViewModel>();
            ViewData["GroupId"] = groupId;
            return View("../Test/List", viewModel);
        }

    }
}

StudyIt.Web/Views/Groups/Choose.cshtml
@{
    ViewBag.Title = "Choose";
}

<ul class="menu">
    <li><a href="/groups/public">Публични</a></li>
    <li><a href="/groups/member-of">На които си член</a></li>
    <li><a href="/groups/not-member-of">На които не си член</a></li>
</ul>

StudyIt.Web/Views/Groups/List.cshtml
@model List<StudyIt.Web.ViewModels.GroupsListViewModel>

@{
    ViewBag.Title = "Групи";
}

<div class="secondaryMenu">
    <ul class="ul-unstyled z-padding">
        @foreach (var group in Model)
        { 
            <li>
                <h3><a href="#" class="show-button" data-target-id="@group.Id" data-target-class="groups-lt">@group.Name</a></h3>

                @if (ViewContext.RouteData.Values["action"].ToString() == "not-member-of")
                {
                    <a href="/members/become/@group.Id">Стани член</a>
                }
                @if (ViewContext.RouteData.Values["action"].ToString() == "member-of" && !group.IsTrainer)
                {
                    <a href="/trainers/become/@group.Id">Стани трейнър</a>
                }
                @if (ViewContext.RouteData.Values["action"].ToString() == "public" && User.Identity.IsAuthenticated && !group.IsTrainer)
                {
                    <a href="/trainers/become/@group.Id">Стани трейнър</a>
                }
                <ul class="ul-unstyled to-show groups-lt" data-id="@group.Id">
                    <li>
                        <a href="/group/@group.Id/lessons">Уроци</a>
                    </li>
                    @if (User.Identity.IsAuthenticated)
                    { 
                        <li>
                            <a href="/group/@group.Id/tests">Тестове</a>
                        </li>
                    }
                </ul>
            </li>
        }
    </ul>
</div>

StudyIt.Web/Views/Groups/Show.cshtml
@model StudyIt.Web.ViewModels.GroupsShowViewModel

@{
    ViewBag.Title = "";
}

<h3>Група @Model.Name</h3>
<div class="float-left">
    <h4>Уроци</h4>
    @{
        Html.RenderAction("ShowLessonsMenu", "Groups", routeValues: new { id = Model.Id });
    }
</div>
@if (User.Identity.IsAuthenticated)
{ 
    <div class="float-left">
        <h4>Тестове</h4>
        @{
    Html.RenderAction("ShowTestsMenu", "Groups", routeValues: new { id = Model.Id });
        }
    </div>
}

StudyIt.Web/Views/Groups/ShowLessonsMenu.cshtml
@model StudyIt.Web.ViewModels.GroupsShowMenuViewModel
<div class="secondaryMenu">
    <ul class="ul-unstyled z-padding">
        @foreach (var category in Model.Categories)
        { 
            <li>
                <h3><a href="#" class="show-button" data-target-class="lesson-subcategory" data-target-id="@category.Id">@category.Name</a></h3>
                <ul class="ul-unstyled to-show lesson-subcategory" data-id="@category.Id">
                    @foreach (var subcategory in category.Subcategories)
                    {
                        <li>
                            <a href="/lesson/list/@subcategory.Id">@subcategory.Name</a>
                        </li>
                    }
                </ul>
            </li>
        }
    </ul>
</div>

StudyIt.Web/Views/Groups/ShowTestsMenu.cshtml
@model StudyIt.Web.ViewModels.GroupsShowMenuViewModel


<div class="secondaryMenu">
    <ul class="ul-unstyled z-padding">
        @foreach (var category in Model.Categories)
        { 
            <li>
                <h3><a href="#" class="show-button" data-target-class="test-subcategory" data-target-id="@category.Id">@category.Name</a></h3>
                <ul class="ul-unstyled to-show test-subcategory" data-id="@category.Id">
                    @foreach (var subcategory in category.Subcategories)
                    {
                        <li>
                            <a href="/test/list/@subcategory.Id">@subcategory.Name</a>
                        </li>
                    }
                </ul>
            </li>
        }
    </ul>
</div>